### ISSUE TITLE
How to display Cards in android application using your BestPracticeForAvs?

### ISSUE THREAD

**Issue by ankiitmaisuria** [JamitLabs/BestPracticeForAVS#4]
I have used you exaple..its working great. I want to displya the Card in android which contain User input and Alexa response in text format in android. Please help me out how can I implement this.

**Comment by DariuschDideban** [comment]
Hi @ankitmaisuriya !
To be serious i have no idea how to do that so far, because the App was made only for Push To Talk like i said in the readme. 
I haven't tried it out and i do not have the time atm but i can only refer to this code, maybe it helps.

https://github.com/alexa/skill-samples-java/tree/master/helloworld/src/com/amazon/asksdk/helloworld

In the HelloWorldExample.java you can see how they create Files for Alexa Skills. Maybe you can use this code somehow.

If you find out how it would be great if you could share your knowledge!
